require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'config/**/*'
    - 'bin/**'
    - 'log/**'
    - 'vendor/**/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: false
